version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloworld-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xgfmbugz89na"
s3_prefix = "helloworld-app"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
